type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
webpack_config = "webpack.config.js"
name = "stripe-workers-backend"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"