name: Test

on:
  pull_request:
    branches: 
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test
        env:
          STRIPE_SECRET_KEY_TEST: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY_TEST: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          DOMAIN_TEST: ${{ secrets.DOMAIN }}